server {
    listen 80;
    root /usr/share/nginx/html;
    index index.csr.html;

    location /api/estoque/ {
        proxy_pass http://host.docker.internal:5001/api/;
    }

    location /api/faturamento/ {
        proxy_pass http://host.docker.internal:5002/api/;
    }

    location / {
        try_files $uri $uri/ /index.csr.html;
    }
}
